/* Auto-generated by build/scripts/gen_fs_caps.py. Do not edit. */
/* Source: src/system/libroot2/fs/fs_caps.json */

#ifndef _NEXUS_FS_CAPS_KERNEL_H
#define _NEXUS_FS_CAPS_KERNEL_H

#include <linux/types.h>
#include <linux/string.h>

#define FS_CAPS_CHECKSUM 0x54d3f414u

#define FS_CAP_PSEUDO     (1u << 0)
#define FS_CAP_PERSISTENT (1u << 1)
#define FS_CAP_READONLY   (1u << 2)
#define FS_CAP_ATTR       (1u << 3)
#define FS_CAP_QUERY      (1u << 4)
#define FS_CAP_NODEMON    (1u << 5)

struct fs_cap_entry {
	const char	*name;
	u32		magic;
	u32		flags;
};

static const struct fs_cap_entry fs_caps_entries[] = {
	{ "ext2", 0x0000ef53u, 0x3au },
	{ "ext3", 0x0000ef53u, 0x3au },
	{ "ext4", 0x0000ef53u, 0x3au },
	{ "xfs", 0x58465342u, 0x3au },
	{ "btrfs", 0x9123683eu, 0x3au },
	{ "f2fs", 0xf2f52010u, 0x3au },
	{ "jfs", 0x3153464au, 0x2au },
	{ "reiserfs", 0x52654973u, 0x2au },
	{ "bcachefs", 0xca451a4eu, 0x2au },
	{ "nilfs2", 0x00003434u, 0x2au },
	{ "zfs", 0x2fc12fc1u, 0x2au },
	{ "ufs", 0x00011954u, 0x22u },
	{ "vfat", 0x00004d44u, 0x22u },
	{ "msdos", 0x00004d44u, 0x22u },
	{ "exfat", 0x2011bab0u, 0x22u },
	{ "ntfs", 0x5346544eu, 0x2au },
	{ "ntfs3", 0x5346544eu, 0x2au },
	{ "fuseblk", 0x65735546u, 0x2au },
	{ "hfs", 0x00004244u, 0x2au },
	{ "hfsplus", 0x0000482bu, 0x2au },
	{ "bfs", 0x42465331u, 0x3au },
	{ "iso9660", 0x00009660u, 0x06u },
	{ "udf", 0x15013346u, 0x02u },
	{ "squashfs", 0x73717368u, 0x0eu },
	{ "erofs", 0xe0f5e1e2u, 0x0eu },
	{ "overlay", 0x794c7630u, 0x28u },
	{ "aufs", 0x61756673u, 0x28u },
	{ "nfs", 0x00006969u, 0x02u },
	{ "cifs", 0xff534d42u, 0x02u },
	{ "fuse", 0x65735546u, 0x00u },
	{ "tmpfs", 0x01021994u, 0x28u },
	{ "ramfs", 0x858458f6u, 0x28u },
	{ "proc", 0x00009fa0u, 0x05u },
	{ "sysfs", 0x62656572u, 0x01u },
	{ "devtmpfs", 0x00001373u, 0x01u },
	{ "devpts", 0x00001cd1u, 0x01u },
	{ "cgroup", 0x0027e0ebu, 0x01u },
	{ "cgroup2", 0x63677270u, 0x01u },
	{ "securityfs", 0x73636673u, 0x01u },
	{ "selinuxfs", 0xf97cff8cu, 0x01u },
	{ "pstore", 0x6165676cu, 0x01u },
	{ "efivarfs", 0xde5e81e4u, 0x01u },
	{ "bpf", 0xcafe4a11u, 0x01u },
	{ "tracefs", 0x74726163u, 0x01u },
	{ "debugfs", 0x64626720u, 0x01u },
	{ "configfs", 0x62656570u, 0x01u },
	{ "fusectl", 0x65735543u, 0x01u },
	{ "hugetlbfs", 0x958458f6u, 0x01u },
	{ "mqueue", 0x19800202u, 0x01u },
	{ "autofs", 0x00000187u, 0x01u },
	{ "rpc_pipefs", 0x67596969u, 0x01u },
	{ "nfsd", 0x6e667364u, 0x01u },
	{ "binfmt_misc", 0x42494e4du, 0x01u },
	{ "nsfs", 0x6e736673u, 0x01u },
	{ "pipefs", 0x50495045u, 0x01u },
	{ "sockfs", 0x534f434bu, 0x01u },
	{ "anon_inodefs", 0x09041934u, 0x01u },
};

static const unsigned int fs_caps_entry_count =
	sizeof(fs_caps_entries)/sizeof(fs_caps_entries[0]);

static inline const struct fs_cap_entry *
fs_caps_kernel_by_name(const char *n)
{
	unsigned int i;
	if (!n)
		return NULL;
	for (i = 0; i < fs_caps_entry_count; i++) {
		if (!strcmp(n, fs_caps_entries[i].name))
			return &fs_caps_entries[i];
	}
	return NULL;
}

static inline bool fs_caps_kernel_is_pseudo(const char *n)
{
	const struct fs_cap_entry *e = fs_caps_kernel_by_name(n);
	return e && (e->flags & FS_CAP_PSEUDO);
}

static inline bool fs_caps_kernel_is_readonly(const char *n)
{
	const struct fs_cap_entry *e = fs_caps_kernel_by_name(n);
	return e && (e->flags & FS_CAP_READONLY);
}

static inline u32 fs_caps_kernel_caps_for(const char *n)
{
	const struct fs_cap_entry *e = fs_caps_kernel_by_name(n);
	return e ? e->flags : 0;
}

#endif
